x-app:
  &default-app
  image: hseeberger/scala-sbt:11.0.13_1.5.7_2.12.15
  working_dir: /app
  volumes:
    - "./:/app"
    - "~/.sbt:/root/.sbt"

services:
  app:
    <<: *default-app
    ports:
      - 8080:8080

  test:
    <<: *default-app
    command: sbt test